export const RESULT_LIST_REQUEST = "RESULT_LIST_REQUEST";
export const RESULT_LIST_SUCCESS = "RESULT_LIST_SUCCESS";
export const RESULT_LIST_FAIL = "RESULT_LIST_FAIL";

export const RESULT_DETAILS_REQUEST = "RESULT_DETAILS_REQUEST";
export const RESULT_DETAILS_SUCCESS = "RESULT_DETAILS_SUCCESS";
export const RESULT_DETAILS_FAIL = "RESULT_DETAILS_FAIL";

export const RESULT_DELETE_REQUEST = "RESULT_DELETE_REQUEST";
export const RESULT_DELETE_SUCCESS = "RESULT_DELETE_SUCCESS";
export const RESULT_DELETE_FAIL = "RESULT_DELETE_FAIL";

export const RESULT_DOWNLOAD_REQUEST = "RESULT_DOWNLOAD_REQUEST";
export const RESULT_DOWNLOAD_SUCCESS = "RESULT_DOWNLOAD_SUCCESS";
export const RESULT_DOWNLOAD_FAIL = "RESULT_DOWNLOAD_FAIL";
