# Generated by Django 3.0.3 on 2021-03-25 10:55

import crosstab.handlers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressModel',
            fields=[
                ('job_id', models.CharField(default=crosstab.handlers.genereate_id, max_length=200, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='crosstab.IPAddressModel')),
            ],
        ),
    ]
