# Generated by Django 3.0.3 on 2021-03-24 17:36

import crosstab.handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressModel',
            fields=[
                ('job_id', models.CharField(default='crosstab-R20210324-173619-1616607379-256654', max_length=200, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crosstab_id', models.CharField(default='crosstab-20210324-173619-1616607379-256654', max_length=200)),
                ('crosstab_image', models.ImageField(upload_to=crosstab.handlers.upload_location)),
                ('crosstab_res_data', models.FileField(null=True, upload_to=crosstab.handlers.upload_location)),
            ],
        ),
    ]
