# Generated by Django 3.0.3 on 2021-03-25 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
