# Generated by Django 3.0.3 on 2021-03-25 14:41

import crosstab.handlers
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0002_resultmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='data',
            field=models.FileField(default=django.utils.timezone.now, upload_to=crosstab.handlers.upload_location),
            preserve_default=False,
        ),
    ]
