# Generated by Django 3.0.3 on 2021-03-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0002_auto_20210324_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='job_id',
            field=models.CharField(default='crosstab-R20210324-174212-1616607732-879029', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='job_id',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='crosstab.IPAddressModel'),
        ),
    ]
