# Generated by Django 3.0.3 on 2021-03-25 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0003_resultmodel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
