# Generated by Django 3.0.3 on 2021-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0003_auto_20210324_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='job_id',
            field=models.CharField(default='crosstab-R20210324-175326-1616608406-127542', max_length=200, primary_key=True, serialize=False),
        ),
    ]
