# Generated by Django 3.0.3 on 2021-03-24 18:00

import crosstab.handlers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0004_auto_20210324_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='job_id',
            field=models.CharField(default=crosstab.handlers.genereate_id, max_length=200, primary_key=True, serialize=False),
        ),
    ]
