# Generated by Django 3.0.3 on 2021-03-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0004_ipaddressmodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 14, 58, 33, 113237)),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 14, 58, 33, 113186)),
        ),
    ]
