# Generated by Django 3.0.3 on 2021-03-28 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0005_auto_20210328_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 4, 48, 422257)),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 4, 48, 422293)),
        ),
    ]
