# Generated by Django 3.0.3 on 2021-03-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0005_auto_20210324_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='crosstab_res_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='crosstab_image',
            new_name='image',
        ),
    ]
