# Generated by Django 3.0.3 on 2021-03-28 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0006_auto_20210328_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 8, 47, 260553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 8, 47, 260586, tzinfo=utc)),
        ),
    ]
