# Generated by Django 3.0.3 on 2021-03-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0006_auto_20210324_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultmodel',
            name='data',
        ),
        migrations.RemoveField(
            model_name='resultmodel',
            name='image',
        ),
    ]
