# Generated by Django 3.0.3 on 2021-03-28 15:09

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0007_auto_20210328_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 9, 0, 901387, tzinfo=utc)),
        ),
    ]
