# Generated by Django 3.0.3 on 2021-03-28 15:49

import crosstab.handlers
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0009_auto_20210328_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressmodel',
            name='title',
            field=models.CharField(default=models.CharField(default=crosstab.handlers.genereate_id, max_length=200, primary_key=True, serialize=False), max_length=200),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 15, 49, 44, 636858, tzinfo=utc)),
        ),
    ]
