# Generated by Django 3.0.3 on 2021-03-28 19:48

import crosstab.handlers
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crosstab', '0010_auto_20210328_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='encodings',
            field=models.FileField(default=django.utils.timezone.now, upload_to=crosstab.handlers.upload_location),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 19, 48, 7, 443145, tzinfo=utc)),
        ),
    ]
