# Generated by Django 3.2.5 on 2021-07-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsmodel',
            name='owner',
        ),
    ]
