export const CROSSTAB_INPUT_SEND_REQUEST = "CROSSTAB_INPUT_SEND_REQUEST";
export const CROSSTAB_INPUT_SEND_SUCCESS = "CROSSTAB_INPUT_SEND_SUCCESS";
export const CROSSTAB_INPUT_SEND_FAIL = "CROSSTAB_INPUT_SEND_FAIL";
