export const RESULT_LIST_REQUEST = "RESULT_LIST_REQUEST";
export const RESULT_LIST_SUCCESS = "RESULT_LIST_SUCCESS";
export const RESULT_LIST_FAIL = "RESULT_LIST_FAIL";

export const RESULT_DETAILS_REQUEST = "RESULT_DETAILS_REQUEST";
export const RESULT_DETAILS_SUCCESS = "RESULT_DETAILS_SUCCESS";
export const RESULT_DETAILS_FAIL = "RESULT_DETAILS_FAIL";

export const DELETE_RESULT = "DELETE_RESULT";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";
