export const TOOL_LIST_REQUEST = "TOOL_LIST_REQUEST";
export const TOOL_LIST_SUCCESS = "TOOL_LIST_SUCCESS";
export const TOOL_LIST_FAIL = "TOOL_LIST_FAIL";

export const TOOL_DETAILS_REQUEST = "TOOL_DETAILS_REQUEST";
export const TOOL_DETAILS_SUCCESS = "TOOL_DETAILS_SUCCESS";
export const TOOL_DETAILS_FAIL = "TOOL_DETAILS_FAIL";
