# Generated by Django 3.2.5 on 2021-08-06 11:02

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('result_id', models.CharField(default=base.models.result_id_generator, max_length=200, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ResultModel',
                'ordering': ('result_id',),
            },
        ),
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('results', models.FileField(null=True, upload_to='files')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.result')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.toolsmodel')),
            ],
            options={
                'verbose_name_plural': 'ResultItemModel',
                'ordering': ('result_id',),
            },
        ),
    ]
